/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/check_roman_numerals.c" instead.
 */

#include <check.h>

#line 1 "tests/check_roman_numerals.c"
#include "../src/roman_numerals.h"

START_TEST(sum2test)
{
#line 4
    char roman_num[16];
    add("I", "I", roman_num);
	// fail_unless(roman_num == "II", "wrong");
	ck_assert_str_eq(roman_num, "II");
	// fail_unless(add("I", "II") == "III", "wrong");
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, sum2test);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
